### ISSUE TITLE
'getBuildProperty' does not work as expected

### ISSUE THREAD

**Issue by NiklasMerz** [apache/cordova-node-xcode#108]
In cordova-ios tests we have some failing tests because `getBuildProperty` behaves strangely.

It loops through all properties and returns the value of the last one. See code:

```javascript
pbxProject.prototype.getBuildProperty = function(prop, build) {
    var target;
    var configs = this.pbxXCBuildConfigurationSection();
    for (var configName in configs) {
        if (!COMMENT_KEY.test(configName)) {
            var config = configs[configName];
            if ( (build && config.name === build) || (build === undefined) ) {
                if (config.buildSettings[prop] !== undefined) {
                    target = config.buildSettings[prop]; // <---- Here
                }
            }
        }
    }
    return target;
}
```

To me this does not make sense. In the cordova-ios test we update and check `PRODUCT_BUNDLE_IDENTIFIER` but we don't update all values. So `getBuildProperty` basically returns a random result. 

Any ideas how we should handle this?

**Comment by erisu** [comment]
@NiklasMerz Do we not need to also update Cordova-iOS to use #109 change correctly? If so, are you going to create that PR and link to this ticket and to #109 PR?

**Comment by NiklasMerz** [comment]
I created a PR for your working branch https://github.com/erisu/cordova-ios/pull/1

**Comment by NiklasMerz** [comment]
Should I create one for upstream?
