### ISSUE TITLE
Error adding resource when a folder called Resource does not exist

### ISSUE THREAD

**Issue by DamienBitrise** [apache/cordova-node-xcode#113]
When calling myProj.addResourceFile() there is a runtime error if there is no folder/Group called 'Resources' in the XCode project.

Proposed Fix: https://github.com/apache/cordova-node-xcode/pull/112

**Comment by hoangDung096** [comment]
After i added the file to project. The file existed in Xcode, but it had light color, also cannot open in xcode. Build fail with: "build input cannot be found .. "

**Comment by timbru31** [comment]
Closed via #112

**Comment by EinfachHans** [comment]
@timbru31 Any chance that you release a new npm version with this?
