### ISSUE TITLE
pbxProject.prototype.addToHeaderSearchPaths

### ISSUE THREAD

**Issue by dreamtravel** [apache/cordova-node-xcode#13]
buildSettings["HEADER_SEARCH_PATHS"]   is  string type , not be array type
in line 1283 and 1285 in pbxProject.js

**Comment by janpio** [comment]
https://github.com/apache/cordova-node-xcode/blob/e7646f0680d509b590b839e567c217590451505b/lib/pbxProject.js#L1283-L1287

What exactly is wrong here?

**Comment by dreamtravel** [comment]
buildSettings["HEADER_SEARCH_PATHS"] is string type , not be array type，cannot work
`
var length = buildSettings["HEADER_SEARCH_PATHS"].length;
var addString = "";
if (typeof file === "string") {
  addString = buildSettings["HEADER_SEARCH_PATHS"].substring(0, length - 1) + " " + file + '"';
} else {
  addString = buildSettings["HEADER_SEARCH_PATHS"].substring(0, length - 1) 
              + " " + searchPathForFile(file, this) + '"';
}
buildSettings["HEADER_SEARCH_PATHS"] = addString;
`

**Comment by JulianKingman** [comment]
@dreamtravel why did you close this? It's still an issue, isn't it? The issue is that sometimes a header_search_path is a string, not an array.

**Comment by brodybits** [comment]
> The issue is that sometimes a header_search_path is a string, not an array.

Please open a new issue if you can find an example where this is the case.

**Comment by JulianKingman** [comment]
@brodybits I have had this occur in my project. I'll try to track the package that uses strings as search paths, but yes, it is a real situation.

**Comment by brodybits** [comment]
@JulianKingman please raise a new issue with [a minimal, complete, verifiable example (mvce) [1]](https://stackoverflow.com/help/mcve) if you can give us a way to reproduce it.

I have labeled this one as an invalid support question since the OP closed it with no reproduction.

[1] <https://stackoverflow.com/help/mcve>
