### ISSUE TITLE
TypeError : Project is getting read as undefined

### ISSUE THREAD

**Issue by anandkumary** [apache/cordova-node-xcode#134]
On running the sample snippet. Framework is repetitively thrown error as `TypeError: Cannot read properties of undefined (reading 'project') `

<img width="813" alt="Screenshot 2022-07-29 at 3 45 47 AM" src="https://user-images.githubusercontent.com/13327077/181646481-a834e021-5295-40f9-a94a-e83907798c21.png">

<img width="534" alt="Screenshot 2022-07-29 at 3 44 51 AM" src="https://user-images.githubusercontent.com/13327077/181646401-8aebdfcc-e34e-4a16-808b-0ae9d523132e.png">

**Comment by abhishekchavda7** [comment]
Getting the same issue. Any one having a lead to resolve the issue.

**Comment by breautek** [comment]
The README snippet shows an example but it isn't runnable code as is. The `projectPath` needs to be a valid path to an actual `pbxproj` file, which RunKit wouldn't have.

If you experience issues running locally with a well-conforming xcode project, then I'd raise a new issue with that context.

**Comment by abhishekchavda7** [comment]
My end goal is that. I have a demo ios project and want to inject a dependencies folder which include sub folder's and swift files.
