### ISSUE TITLE
allow setting empty path

### ISSUE THREAD

**Issue by n1ru4l** [apache/cordova-node-xcode#23]
When path is set to `undefiend` or `null` the following code is generated:

```
8E63D5C4EFE34B3BAE93815F /* Frameworks */ = {
			isa = PBXGroup;
			children = (
				18285FBD1A3D4F05A3F47AC4 /* GoogleInterchangeUtilities.framework */,
			);
			name = Frameworks;
			path = undefined;
			sourceTree = "<group>";
		};
```

Since it is possible to create groups without a path it would be nice to not set a path when the path is `undefined` or `null`. Furthermore a path that equals `undefined` or `null` makes the Group appear red in xcode. This would also be fixed by simply dropping the path

**Comment by janpio** [comment]
Can you share the code used to produce this? Would make finding the correct parts of the library to change a lot easier. Thanks.

**Comment by n1ru4l** [comment]
@janpio I used `addFramework` on a `pbxProject` instance, but it also happens when using `addPbxGroup` on a `pbxProject` instance (which is used by `addFramework`).

**Comment by janpio** [comment]
So https://github.com/apache/cordova-node-xcode/blob/d1ff114a9495743dc3ca1a965d590e2f186e40a7/lib/pbxProject.js#L317-L362 and https://github.com/apache/cordova-node-xcode/blob/d1ff114a9495743dc3ca1a965d590e2f186e40a7/lib/pbxProject.js#L494-L543

The solution would be to change the latter to check if a path is provided, and if not drop the `path` key from the array?

**Comment by n1ru4l** [comment]
What about https://github.com/apache/cordova-node-xcode/commit/57e6e982bfd5425f3466f3d128e75b69159e6368?
