### ISSUE TITLE
Can we have a release? :)

### ISSUE THREAD

**Issue by fbartho** [apache/cordova-node-xcode#50]
There are some neat fixes that have happened since the last release. I'd be happy to become a contributor if you need somebody to do the grunt-work of shipping a release!

**Comment by fbartho** [comment]
Bump! -- Not sure if you're the one to beg on this one @brodybits :)

**Comment by brodybits** [comment]
I just saw this, will probably need a few weeks to get around to it.

You can always ping us at <dev@cordova.apache.org>. I suspect all maintainers would be overloaded like myself.

**Comment by brodybits** [comment]
I hope we can do this in the next 1-2 weeks or so. Please do us a favor and ping us at dev@cordova.apache.org if you do not see the release within the next several weeks.

**Comment by fbartho** [comment]
@brodybits -- Shot an e-mail to that address just now!

**Comment by brodybits** [comment]
Thanks @fbartho. I cannot make the proper release until I get my mac back from repair.

I hope another maintainer can make the release soon.

**Comment by fbartho** [comment]
Bummer on your dead machine @brodybits!

**Comment by l3ender** [comment]
Friendly bump. :)

**Comment by brodybits** [comment]
I still don't have my machine back, suggest you guys follow up on the mailing list, see <https://cordova.apache.org/contact/>

**Comment by brodybits** [comment]
I just sent [this message](https://lists.apache.org/thread.html/e1f1b7975835a1036ed52b21cbdf8683f02087391bc1fec94d864425@%3Cdev.cordova.apache.org%3E) to the mailing list. I make the new release within the next few days, assuming no objections, will need to go through the Apache Cordova voting process before publishing it.

Thanks to all for your patience with me.

**Comment by fbartho** [comment]
Thanks!! I had written to the mailing list, but had not subscribed to it. So it strikes me now that I probably missed any replies. 

(It’s been a while since I participated in a classic style mailing list. My bad!)

**Comment by brodybits** [comment]
I just published xcode@2.1.0 after going through the package review process. Thanks for the patience!
