### ISSUE TITLE
WatchKit2 and WatchApp2 not supported

### ISSUE THREAD

**Issue by l3ender** [apache/cordova-node-xcode#55]
Newer apps that want to use WatchKit2 are not currently supported.

https://github.com/apache/cordova-node-xcode/blob/a65e1943ed8c71d93e4c673d0a7aabf4ebca7623/lib/pbxProject.js#L1699
https://github.com/apache/cordova-node-xcode/blob/a65e1943ed8c71d93e4c673d0a7aabf4ebca7623/lib/pbxProject.js#L1700

I'll be opening a PR as I'm working on this.

**Comment by brodybits** [comment]
Thanks @l3ender for the PR, it is currently under review. My apologies for the lack of response.
