### ISSUE TITLE
Travis CI build is too slow (was stuck)

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-node-xcode#60]
I really do not understand it. I just pushed a new `brodybits-travis-ci-multiple-os` branch, Travis CI seems to be ~~stuck~~ __too slow__. I pushed the same branch to my fork, with Travis CI there, and _quickly_ got a green build.

**Comment by timbru31** [comment]
Could you possibly put a link to the "stuck" TravisCI build?

**Comment by brodybits** [comment]
Well it did seem to solve itself, still too slow I think.
