### ISSUE TITLE
[MAJOR] Drop support for Node.js 6 & 8

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-node-xcode#77]
It is not desired to support outdated Node.js versions unless absolutely necessary.

For example, test coverage in PR #76 needed to be adapted to work on Node.js 6.

This kind of breaking change needs to be done in a major release. We would likely remove Node.js 8 at the same time since its EOL is December 2019.

**Comment by timbru31** [comment]
PR's: #91 #92 #90
